AllCops:
  TargetRubyVersion: 2.6.3
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/config.ru'
    - '**/*.rake'
  Exclude:
    - vendor/**/*
    - db/migrations/**/*

  DisplayCopNames:
    Enabled: true

  DisplayStyleGuide:
    Enabled: true

Naming/FileName:
  Exclude:
  - Guardfile
  - Vagrantfile
  - test/Vagrantfile
  - Dockerfile

Metrics/BlockLength:
  Exclude:
    - spec/**/*
